import { Fragment } from "react";
import "./FooterText.css";

const FooterText = () => {
  return (
    <Fragment>
      <div className="text-xs mt-12">
        &copy; Copyright {new Date().getFullYear()} Public Holdings, Inc. All Rights Reserved.
      </div>
      <section className="text-xs my-4">
        “Zero-commission” or “commission-free” means $0 commission for Open to the Public Investing, Inc. self-directed individual brokerage accounts that trade U.S. listed securities electronically. Other fees may apply. See our <a href="/" className="text-primary transition-all font-medium hover:underline">Fee Schedule</a> for more information.
      </section>

      <section className="my-4 text-xs">
        This is not an offer, solicitation of an offer or advice to buy or sell securities, or open a brokerage account in any jurisdiction where Open to the Public Investing, Inc is not registered.
      </section>

      <section className="my-4 text-xs">
        Open to the Public Investing, Inc does not recommend any securities. All investments involve risk and the past performance of a security or financial product does not guarantee future results or returns. Keep in mind that while diversification may help spread risk it does not assure a profit, or protect against loss, in a down market. There is always the potential of losing money when you invest in securities or other financial products. Investors should consider their investment objectives and risks carefully before investing.
      </section>

      <section className="my-4 text-xs">
        The above content is provided for general informational purposes only. It is not intended to constitute investment advice or any other kind of professional advice and should not be relied upon as such. Before taking action based on any such information, we encourage you to consult with the appropriate professionals. We do not endorse any third parties referenced within the article. Market and economic views are subject to change without notice and may be untimely when presented here. Do not infer or assume that any securities, sectors or markets described in this article were or will be profitable. Past performance is no guarantee of future results. There is a possibility of loss. Historical or hypothetical performance results are presented for illustrative purposes only<br/>
        Investors should be aware that system response, execution price, speed, liquidity, market data, and account access times are affected by many factors, including market volatility, size and type of order, market conditions, system performance, and other factors. These risks are to be assumed by the customer. For additional information on data provided within the App, please see our Data Disclosure.
      </section>

      <section className="my-4 text-xs">
        Investors should consider the investment objectives and unique risk profile of Exchange Traded Funds (ETFs) carefully before investing. ETFs are subject to risks similar to those of other diversified portfolios. Leveraged and Inverse ETFs may not be suitable for all investors and may increase exposure to volatility through the use of leverage, short sales of securities, derivatives and other complex investment strategies.<br/>
        Although ETFs are designed to provide investment results that generally correspond to the performance of their respective underlying indices, they may not be able to exactly replicate the performance of the indices because of expenses and other factors. A prospectus contains this and other information about the ETF and should be read carefully before investing. Customers should obtain prospectuses from issuers and/or their third party agents who distribute and make prospectuses available for review. ETFs are required to distribute portfolio gains to shareholders at year-end. These gains may be generated by portfolio rebalancing or the need to meet diversification requirements. ETF trading will also generate tax consequences. Additional regulatory guidance on Exchange Traded Products can be found by clicking <a href="/" className="text-primary transition-all font-medium hover:underline">clicking here</a>.
      </section>

      <section className="my-4 text-xs">
        Third-party information provided for Open to the Public Investing, Inc product features, Open to the Public Investing, Inc communications and communications emanating from its social media community, market prices, data and other information available through Open to the Public Investing, Inc are meant for informational purposes only and are not intended as an offer or solicitation for the purchase or sale of any financial instrument or as an official confirmation of any transaction. The information provided is not warranted as to completeness or accuracy and is subject to change without notice. The Open to the Public Investing, Inc website provides its users' links to social media sites and email. The linked social media and email messages are pre-populated. However, these messages can be deleted or edited by Open to the Public Investing, Inc users, who are under no obligation to send any pre-populated messages. Any comments or statements made herein do not reflect the views of Open to the Public Investing, Inc or any of its subsidiaries or affiliates. Note that certain Open to the Public Investing, Inc product features listed are currently in development and will be available soon. Open to the Public Investing, Inc., may receive payment for order flow through third parties.
      </section>

      <section className="my-4 text-xs">
        All securities and investments are offered to self-directed customers by Open to the Public Investing, Inc, member FINRA & SIPC. Additional information about your broker can be found by <a href="/" className="text-primary transition-all font-medium hover:underline">clicking here</a>. Open to the Public Investing, Inc is a wholly-owned subsidiary of Public Holdings Inc. 
      </section>
      <section className="my-4 text-xs">
        Public.com provides cryptocurrency trading through Apex Crypto. Apex Crypto is not a registered broker-dealer or FINRA member. Cryptocurrencies are not securities and your cryptocurrency holdings are not FDIC or SIPC insured. Crypto trading involves substantial risk of loss and there can be significant volatility in the price of cryptocurrencies. Cryptocurrency trading is not suitable for all investors and each investor should evaluate their own particular financial circumstances to determine whether trading cryptocurrencies is appropriate for them. Crypto trading is not yet available for New York state residents. Please ensure that you fully understand <a href="/" className="text-primary transition-all font-medium hover:underline">the risks involved</a> before trading.
      </section>

      <section className="mt-4 mb-22 text-xs">
        <a href="/" className="font-medium text-primary transition-all hover:underline">View Full Disclosures</a>
      </section>
    </Fragment>
  );
}

export default FooterText;
